version: '3.8'

services:
  mcp-gateway:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
      args:
        NODE_VERSION: 18.20.5
        ALPINE_VERSION: 3.20
    image: mcp-gateway:latest
    container_name: mcp-gateway-server
    restart: unless-stopped
    ports:
      - "3333:3333"
    environment:
      NODE_ENV: production
      PORT: 3333
      LOG_LEVEL: info
      # Add other environment variables here or use env_file
    env_file:
      - .env
    volumes:
      # Logs volume for persistent logging
      - ./logs:/app/logs:rw
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3333/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M
    networks:
      - mcp-network
    read_only: true
    tmpfs:
      - /tmp:noexec,nosuid,size=100M
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE

  # Development service (optional)
  mcp-gateway-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    image: mcp-gateway:dev
    container_name: mcp-gateway-dev
    profiles:
      - dev
    ports:
      - "3334:3333"
    environment:
      NODE_ENV: development
      PORT: 3333
      LOG_LEVEL: debug
    env_file:
      - .env
    volumes:
      # Mount source code for hot reload
      - ./src:/app/src:ro
      - ./package.json:/app/package.json:ro
      - ./tsconfig.json:/app/tsconfig.json:ro
      - ./logs:/app/logs:rw
    command: ["npm", "run", "dev"]
    networks:
      - mcp-network

networks:
  mcp-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

# Volumes for persistent data (optional)
volumes:
  logs:
    driver: local