[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
numReplicas = 1

[[deploy.services]]
name = "worker"
internalPort = 8080
protocol = "http"

[env]
# These will be overridden by Railway environment variables
HEALTH_CHECK_ENABLED = "true"
HEALTH_CHECK_PORT = "8080"
WORKER_ID = "railway-worker-1"
LOG_LEVEL = "INFO"